sudo: required
language: generic
services:
    - docker
    
before install:
    - docker build -t 360154266/react-test -f ./client/Dockerfile.dev ./client
        
script:
    - docker run -e CI=true 360154266/react-test npm test
              
after_success:
    - docker build -t 360154266/multi-client ./client
    - docker build -t 360154266/multi-nginx ./nginx
    - docker build -t 360154266/multi-server ./server
    - docker build -t 360154266/multi-worker ./worker
        
    # Log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Take images and push into docker
    
    - docker push 360154266/multi-client
    - docker push 360154266/multi-nginx
    - docker push 360154266/multi-server
    - docker push 360154266/multi-worker